version: "3.9"

services:

  nodejs:
    build: ./node
    container_name: nodejs
    ports:
      - "3000:3000"
    depends_on:
      - python

  python:
    build: ./python-app
    container_name: python
    ports:
      - "5000:5000"
    depends_on:
      - php

  php:
    build: ./php-app
    container_name: php
    ports:
      - "8082:80"
    volumes:
      - ./php-app:/var/www/html
    depends_on:
      - mysql

  mysql:
    build: ./mysql-db
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    depends_on:
      - ngnix

  ngnix:
    build: ./nginx-app
    container_name: ngnix
    ports:
      - "8081:80"
    depends_on:
      - mongodb

  mongodb:
    build: ./mongodb-app
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
    depends_on:
      - rabbitmq

  rabbitmq:
    build: ./rabbitMQ
    container_name: rabbitmq
    ports:
      - "5673:5672"   
      - "15673:15672" 
    depends_on:
      - redis

  redis:
    build: ./redis
    container_name: redis
    ports:
      - "6380:6379"
    depends_on:
      - apache
  apache:
    build: ./apache
    container_name: apache
    ports:
      - "8083:80"
    depends_on:
      - java
  java:
    build: ./java
    container_name: java
    ports:
      - "9090:9090"